// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOIer_46FGF5ZgzwNi9qe8O1oFZLGDhX8',
    appId: '1:1030173625945:web:b156dd0c0b9f8de992eb48',
    messagingSenderId: '1030173625945',
    projectId: 'practice-90339',
    authDomain: 'practice-90339.firebaseapp.com',
    databaseURL: 'https://practice-90339-default-rtdb.firebaseio.com',
    storageBucket: 'practice-90339.appspot.com',
    measurementId: 'G-S1MEJ7RN3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6aKGHyFRoPuhHoTKsm8ra9HsuIqqByMo',
    appId: '1:1030173625945:android:ff237157cc817f8592eb48',
    messagingSenderId: '1030173625945',
    projectId: 'practice-90339',
    databaseURL: 'https://practice-90339-default-rtdb.firebaseio.com',
    storageBucket: 'practice-90339.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4cy2orJwjqC-wtiU7Y-7Y1UFrNJ8cBKA',
    appId: '1:1030173625945:ios:1c42dc836f0552ac92eb48',
    messagingSenderId: '1030173625945',
    projectId: 'practice-90339',
    databaseURL: 'https://practice-90339-default-rtdb.firebaseio.com',
    storageBucket: 'practice-90339.appspot.com',
    iosBundleId: 'com.example.sparkle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4cy2orJwjqC-wtiU7Y-7Y1UFrNJ8cBKA',
    appId: '1:1030173625945:ios:a800b7637a04e27692eb48',
    messagingSenderId: '1030173625945',
    projectId: 'practice-90339',
    databaseURL: 'https://practice-90339-default-rtdb.firebaseio.com',
    storageBucket: 'practice-90339.appspot.com',
    iosBundleId: 'com.example.sparkle.RunnerTests',
  );
}
