// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEJVM0X2DqHLhjLi75rv-VmFBDhj8tJrc',
    appId: '1:222788339668:web:58923f3addbb5ddb9e3841',
    messagingSenderId: '222788339668',
    projectId: 'gdsc-ku-sparkle',
    authDomain: 'gdsc-ku-sparkle.firebaseapp.com',
    databaseURL: 'https://gdsc-ku-sparkle-default-rtdb.firebaseio.com',
    storageBucket: 'gdsc-ku-sparkle.appspot.com',
    measurementId: 'G-4YRS38JL1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSfTBXP81L8ZX3QQiRVhuRKBFj7RJIceo',
    appId: '1:222788339668:android:f9d4e7c5a884ca199e3841',
    messagingSenderId: '222788339668',
    projectId: 'gdsc-ku-sparkle',
    databaseURL: 'https://gdsc-ku-sparkle-default-rtdb.firebaseio.com',
    storageBucket: 'gdsc-ku-sparkle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTJaGEXcK33IMtgPDrvqCzD1AZOvuB5qM',
    appId: '1:222788339668:ios:04834c02f252cbe69e3841',
    messagingSenderId: '222788339668',
    projectId: 'gdsc-ku-sparkle',
    databaseURL: 'https://gdsc-ku-sparkle-default-rtdb.firebaseio.com',
    storageBucket: 'gdsc-ku-sparkle.appspot.com',
    iosBundleId: 'com.example.sparkle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTJaGEXcK33IMtgPDrvqCzD1AZOvuB5qM',
    appId: '1:222788339668:ios:2a4ee80a3384417d9e3841',
    messagingSenderId: '222788339668',
    projectId: 'gdsc-ku-sparkle',
    databaseURL: 'https://gdsc-ku-sparkle-default-rtdb.firebaseio.com',
    storageBucket: 'gdsc-ku-sparkle.appspot.com',
    iosBundleId: 'com.example.sparkle.RunnerTests',
  );
}
